version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - "saharshy29"
    assignees:
      - "saharshy29"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    commit-message:
      prefix: "ï¸dependabot:"
    schedule:
      interval: "daily"